// Generated by `wit-bindgen` 0.13.0. DO NOT EDIT!
#include "foo.h"

__attribute__((__weak__, __export_name__("cabi_post_concat")))
void __wasm_export_foo_concat_post_return(int32_t arg0) {
  if ((*((int32_t*) (arg0 + 4))) > 0) {
    free((void*) (*((int32_t*) (arg0 + 0))));
  }
}

__attribute__((__weak__, __export_name__("cabi_realloc")))
void *cabi_realloc(void *ptr, size_t old_size, size_t align, size_t new_size) {
  (void) old_size;
  if (new_size == 0) return (void*) align;
  void *ret = realloc(ptr, new_size);
  if (!ret) abort();
  return ret;
}

// Helper Functions

void foo_string_set(foo_string_t *ret, char*s) {
  ret->ptr = (uint8_t*) s;
  ret->len = strlen(s);
}

void foo_string_dup(foo_string_t *ret, const char*s) {
  ret->len = strlen(s);
  ret->ptr = cabi_realloc(NULL, 0, 1, ret->len * 1);
  memcpy(ret->ptr, s, ret->len * 1);
}

void foo_string_free(foo_string_t *ret) {
  if (ret->len > 0) {
    free(ret->ptr);
  }
  ret->ptr = NULL;
  ret->len = 0;
}

// Component Adapters

__attribute__((__aligned__(4)))
static uint8_t RET_AREA[8];

__attribute__((__export_name__("concat")))
int32_t __wasm_export_foo_concat(int32_t arg, int32_t arg0, int32_t arg1, int32_t arg2) {
  foo_string_t arg3 = (foo_string_t) { (uint8_t*)(arg), (size_t)(arg0) };
  foo_string_t arg4 = (foo_string_t) { (uint8_t*)(arg1), (size_t)(arg2) };
  foo_string_t ret;
  foo_concat(&arg3, &arg4, &ret);
  int32_t ptr = (int32_t) &RET_AREA;
  *((int32_t*)(ptr + 4)) = (int32_t) (ret).len;
  *((int32_t*)(ptr + 0)) = (int32_t) (ret).ptr;
  return ptr;
}

__attribute__((__export_name__("add")))
int32_t __wasm_export_foo_add(int32_t arg, int32_t arg0) {
  uint8_t ret = foo_add((uint8_t) (arg), (uint8_t) (arg0));
  return (int32_t) (ret);
}

extern void __component_type_object_force_link_foo(void);
void __component_type_object_force_link_foo_public_use_in_this_compilation_unit(void) {
  __component_type_object_force_link_foo();
}
