// Generated by `wit-bindgen` 0.13.0. DO NOT EDIT!
const _: () = {
  
  #[doc(hidden)]
  #[export_name = "concat"]
  #[allow(non_snake_case)]
  unsafe extern "C" fn __export_concat(arg0: i32,arg1: i32,arg2: i32,arg3: i32,) -> i32 {
    #[allow(unused_imports)]
    use wit_bindgen::rt::{alloc, vec::Vec, string::String};
    
    // Before executing any other code, use this function to run all static
    // constructors, if they have not yet been run. This is a hack required
    // to work around wasi-libc ctors calling import functions to initialize
    // the environment.
    //
    // This functionality will be removed once rust 1.69.0 is stable, at which
    // point wasi-libc will no longer have this behavior.
    //
    // See
    // https://github.com/bytecodealliance/preview2-prototyping/issues/99
    // for more details.
    #[cfg(target_arch="wasm32")]
    wit_bindgen::rt::run_ctors_once();
    
    let len0 = arg1 as usize;
    let bytes0 = Vec::from_raw_parts(arg0 as *mut _, len0, len0);
    let len1 = arg3 as usize;
    let bytes1 = Vec::from_raw_parts(arg2 as *mut _, len1, len1);
    let result2 = <_GuestImpl as Guest>::concat(wit_bindgen::rt::string_lift(bytes0), wit_bindgen::rt::string_lift(bytes1));
    let ptr3 = _RET_AREA.0.as_mut_ptr() as i32;
    let vec4 = (result2.into_bytes()).into_boxed_slice();
    let ptr4 = vec4.as_ptr() as i32;
    let len4 = vec4.len() as i32;
    ::core::mem::forget(vec4);
    *((ptr3 + 4) as *mut i32) = len4;
    *((ptr3 + 0) as *mut i32) = ptr4;
    ptr3
  }
  
  const _: () = {
    #[doc(hidden)]
    #[export_name = "cabi_post_concat"]
    #[allow(non_snake_case)]
    unsafe extern "C" fn __post_return_concat(arg0: i32,) {
      let l0 = *((arg0 + 0) as *const i32);
      let l1 = *((arg0 + 4) as *const i32);
      wit_bindgen::rt::dealloc(l0, (l1) as usize, 1);
    }
  };
};
use foo as _GuestImpl;
pub trait Guest {
  fn concat(left: wit_bindgen::rt::string::String,right: wit_bindgen::rt::string::String,) -> wit_bindgen::rt::string::String;
}

#[allow(unused_imports)]
use wit_bindgen::rt::{alloc, vec::Vec, string::String};

#[repr(align(4))]
struct _RetArea([u8; 8]);
static mut _RET_AREA: _RetArea = _RetArea([0; 8]);

#[cfg(target_arch = "wasm32")]
#[link_section = "component-type:foo"]
#[doc(hidden)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 183] = [3, 0, 3, 102, 111, 111, 0, 97, 115, 109, 13, 0, 1, 0, 7, 55, 1, 65, 2, 1, 65, 2, 1, 64, 2, 4, 108, 101, 102, 116, 115, 5, 114, 105, 103, 104, 116, 115, 0, 115, 4, 0, 6, 99, 111, 110, 99, 97, 116, 1, 0, 4, 1, 15, 101, 120, 97, 109, 112, 108, 101, 58, 102, 111, 111, 47, 102, 111, 111, 4, 0, 11, 21, 1, 1, 15, 101, 120, 97, 109, 112, 108, 101, 58, 102, 111, 111, 47, 119, 105, 116, 3, 0, 0, 0, 16, 12, 112, 97, 99, 107, 97, 103, 101, 45, 100, 111, 99, 115, 0, 123, 125, 0, 69, 9, 112, 114, 111, 100, 117, 99, 101, 114, 115, 1, 12, 112, 114, 111, 99, 101, 115, 115, 101, 100, 45, 98, 121, 2, 13, 119, 105, 116, 45, 99, 111, 109, 112, 111, 110, 101, 110, 116, 6, 48, 46, 49, 54, 46, 48, 15, 119, 105, 116, 45, 98, 105, 110, 100, 103, 101, 110, 45, 122, 105, 103, 6, 48, 46, 49, 51, 46, 48];

#[inline(never)]
#[doc(hidden)]
#[cfg(target_arch = "wasm32")]
pub fn __link_section() {}
