// Generated by `wit-bindgen` 0.13.0. DO NOT EDIT!
#ifndef __BINDINGS_HOST_H
#define __BINDINGS_HOST_H
#ifdef __cplusplus
extern "C" {
#endif

#include <stdlib.h>
#include <stdint.h>
#include <stdbool.h>

// Exported Functions from `host`
void host_run(void);

#ifdef __cplusplus
}
#endif
#endif
